### ISSUE TITLE
AI Creation fails, formatting error?

### ISSUE THREAD

**Issue by ArcDargo** [compujuckel/AssettoServer#10]
[https://imgur.com/a/ZGpdjO5](url)
![image](https://user-images.githubusercontent.com/22106143/150663741-d3171f90-3a96-4d8c-a191-23579c4ac6a9.png)
So when trying to make even one AI for the server, we kept getting errors that it couldn't even pull in the file, unsure if this is a format issue in the config or an error in the CS files for the sever.

**Comment by compujuckel** [comment]
Read the readme again carefully, the `AI=` parameter must be added to your entry list, not into `fast_lane.ai`.
`fast_lane.ai` is a binary file that you must download separately for your map. For SRP it can be found in the srp-track-extras channel on the SRP discord.


Please visit #server-troubleshooting on our Discord if you need further installation help.
