### ISSUE TITLE
Ipv6 Suppoer

### ISSUE THREAD

**Issue by Fernichter** [compujuckel/AssettoServer#101]
Hi, 
would it be possible to add ipv6 support or is there any configuration I can make to enable ipv6 support?

Thanks

**Comment by thisguyStan** [comment]
Did you test acServer with IPv6? 
In a super short test i couldn't get it to work.
So i'm more so questioning if AC itself supports IPv6, but i haven't looked into that myself.

**Comment by compujuckel** [comment]
Yeah pretty sure AC doesn't support IPv6.
