### ISSUE TITLE
Does not work with alternate file path

### ISSUE THREAD

**Issue by supedog** [compujuckel/AssettoServer#17]
Folder permissions seem ok

14:10:57.033: > [14:10:57 INF] AssettoServer 0.0.47+e7a31c5240
14:10:57.210: > [14:10:57 INF] Starting server
14:10:57.250: > [14:10:57 INF] Loaded 4 cars
14:10:57.381: > [14:10:57 DBG] Added checksum for system/data/surfaces.ini
14:10:57.394: > [14:10:57 FTL] Unhandled exception occurred
14:10:57.396: > System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Games\Steam\steamapps\common\assettocorsa\server\content\tracks\shuto_revival_project_beta'.
14:10:57.397: >    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
14:10:57.397: >    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
14:10:57.397: >    at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
14:10:57.399: >    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
14:10:57.400: >    at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
14:10:57.400: >    at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
14:10:57.401: >    at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
14:10:57.401: >    at System.IO.Directory.GetFiles(String path)
14:10:57.402: >    at AssettoServer.Server.ChecksumsProvider.ChecksumDirectory(Builder builder, String directory) in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Server/ChecksumsProvider.cs:line 73
14:10:57.403: >    at AssettoServer.Server.ChecksumsProvider.CalculateTrackChecksums(String track, String trackConfig) in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Server/ChecksumsProvider.cs:line 31
14:10:57.403: >    at AssettoServer.Server.ACServer.InitializeChecksums() in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Server/ACServer.cs:line 577
14:10:57.403: >    at AssettoServer.Server.ACServer..ctor(ACServerConfiguration configuration, ACPluginLoader loader) in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Server/ACServer.cs:line 312
14:10:57.404: >    at AssettoServer.Program.Main(String[] args) in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Program.cs:line 90
14:10:57.404: >    at AssettoServer.Program.<Main>(String[] args)
14:10:57.482: → Stopped: 1

**Comment by compujuckel** [comment]
are you sure that the path `C:\Games\Steam\steamapps\common\assettocorsa\server\content\tracks\shuto_revival_project_beta` exists? note the **server** in there
