### ISSUE TITLE
UDP Plugin Support

### ISSUE THREAD

**Issue by razaqq** [compujuckel/AssettoServer#23]
Basically the server opens a udp port an sends/receives packets from there

The entire protocol is documented here
https://github.com/minolin/acplugins/tree/master/acplugins4net

some of the packets are equal to the ones you are sending to clients
https://github.com/compujuckel/AssettoServer/tree/master/AssettoServer/Network/Packets
but most will need to be implemented

**Comment by compujuckel** [comment]
Merged #30, thanks again for your work :)
