### ISSUE TITLE
AssettoServer.exe Won't Run

### ISSUE THREAD

**Issue by iixCarbonxZz** [compujuckel/AssettoServer#27]
I have moved some server files over to the folder for AssettoServer but when I try to run the executable normally or as admin nothing runs. i have also tried moving the folder to downloads from where it is currently which is within the steamapps\common folder alongside AC.

I have version 0.0.48-fix1.

**Comment by compujuckel** [comment]
Hi, check server logs and please read this: https://github.com/compujuckel/AssettoServer#getting-help=
