### ISSUE TITLE
config dir

### ISSUE THREAD

**Issue by QuintenQVD0** [compujuckel/AssettoServer#55]
When you execute the binary for the first time it tells you that it is missing the server_config.ini in the cfg folder
so if you make the cfg folder and go in to it and put your config file there. then you try to execute the binary with ../AssettoServer to tells you that the config file is not found in cfg/cfg/

So for example my server files are in /home/ubuntu/server if I then execute the bin it tells me that there is no config in:  /home/ubuntu/server/cfg . If you go in to  /home/ubuntu/server/cfg, make the config file and then run ../AssettoServer it tells me there is no config file in: /home/ubuntu/server/cfg/cfg. 

The server should always look for the cfg folder from where the binary is located. not from the current dir

**Comment by compujuckel** [comment]
I disagree, config files might not always be located next to the binary, for example in the Docker image.

**Comment by QuintenQVD0** [comment]
clearly you did not read. or I was not clear

**Comment by compujuckel** [comment]
Pretty sure I understood you correctly, but I still disagree.
Just take a look at https://github.com/compujuckel/AssettoServer/blob/master/docker/Dockerfile
The server is located in /app, while the config is mounted to /data. How is that going to work if config must always be in the same folder as the binary?

**Comment by QuintenQVD0** [comment]
> Pretty sure I understood you correctly, but I still disagree. Just take a look at https://github.com/compujuckel/AssettoServer/blob/master/docker/Dockerfile The server is located in /app, while the config is mounted to /data. How is that going to work if config must always be in the same folder as the binary?

must application require the config file as you do in a sub folder like cfg. but as in docker if the bin dir is not writable they have a flag for specifying the config location. 
It is just if I am for example in /home/ubuntu then my config has to be in /home/ubuntu/cfg but I am in /opt then I still have to have that config file in /opt/cfg  while my bin is still in /home/ubuntu/server. That is wy most games / aplication do it relative to the bin and else you specify it for example with --config

**Comment by compujuckel** [comment]
`-c` and `-e` flags already exist to specify config locations (required for CM compatibility) and using the working directory otherwise seems like a sensible default IMHO.

**Comment by QuintenQVD0** [comment]
I don't agree but fine. You are the dev you make the disissions
